[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "edwarp"
description = "Python-only static file (js, css) bundler core library"
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [
  { name = "Robin van der Noord", email = "robin.vdn@educationwarehouse.nl" },
  { name = "Remco Boerma", email = "remco.b@educationwarehouse.nl" }
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]


dependencies = [
  "tomlkit",
  "python-dotenv",
  "sassquatch>=1.0.1",
  "rjsmin",
  "edwh-quickjs-ng >= 0.14.0.3",
  "requests",
  "pyyaml",
  "configuraptor>=1.28.0",
  "expandvars<2",
  "termcolor"
]
version = "0.1.0"

[project.optional-dependencies]
dev = [
    "hatch",
    # "black",
    "pytest",
]

[project.urls]
Documentation = "https://github.com/educationwarehouse/edwarp#readme"
Issues = "https://github.com/educationwarehouse/edwarp/issues"
Source = "https://github.com/educationwarehouse/edwarp"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.hatch.build.targets.wheel]
packages = ["src/edwarp"]

[tool.vommit]
allow_breaking_bang = true
allow_breaking_footer = true
prerelease_token = "beta"
confirm = true

[tool.vommit.git]
enabled = true
origin = "origin"
branch = "master"
on_wrong_branch = "error"
tag_format = "v{version}"
commit_format = "{version}"

[tool.vommit.changelog]
enabled = true
file = "CHANGELOG.md"
include_prereleases = false
placeholder = "<!--next-version-placeholder-->"
placeholder_regex = "<auto>"
entry_title_format = "## v{version} ({date:%Y-%m-%d})"

[tool.vommit.changelog.levels]
feat = "Feature{s}"
fix = "Fix{es}"
break = "Breaking Change{s}"
docs = "Documentation"
perf = "Performance"

[tool.vommit.pypi]
enabled = true
use_keyring = true

[tool.vommit.commands]
clean = "rm -rf ./dist"
build = "hatch build"
publish = "uv publish"
post_publish = ""

[tool.vommit.version_bump_map]
break = "major"
build = "patch"
chore = "patch"
feat = "minor"
fix = "patch"
perf = "patch"
refactor = "patch"

[tool.black]
target-version = ["py312"]
line-length = 120
skip-string-normalization = false

[tool.ruff]
target-version = "py312"
line-length = 120

[tool.ruff.lint]
select = [
    "F", # pyflake error
    "E", # pycodestyle error
    "W", # pycodestyle warning
    "Q", # quotes
    "A", # builtins
    # "C4", # comprehensions - NO: doesn't allow dict()
    # "RET", # return - NO: annoying
    "SIM", # simplify
    "ARG", # unused arguments
    # "COM", # comma's - NO: annoying
    # "PTH", # use pathlib - NO: annoying
    "RUF", # ruff rules
]
unfixable = [
    # Don't touch unused imports
    "F401",
]

ignore = [
    "RUF013" # implicit Optional
]

[tool.isort]
profile = "black"
extend_skip_glob = ["*.bak/*"]
